jobs:
- name: build-jekyll
  public: true
  plan:
  - get: repository
    trigger: true
  - get: gist
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: praqma/gh-pages}
      inputs:
        - name: repository
        - name: gist
      outputs:
        - name: site
      run:
        path: sh
        args:
        - -exc
        - |
           git clone gist site
           cd repository && jekyll build && cp _site/* ../site && cd ../site
           git config --global user.email "nobody@special.praqma"
           git config --global user.name "praqma" && git add .
           git commit -m "updated gist"
    on_failure:
      put: slack-alert
      params:
        channel: '@albert'
        text: |
          The build failed. Please go correct it at:
          http://35.156.129.15//teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          http://35.156.129.15//builds/$BUILD_ID
  - put: gist
    params:
      repository: site


- name: test-site
  public: true
  plan:
  - get: repository
    passed: [build-jekyll]
    trigger: true
  - task: curl-site
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: praqma/gh-pages
      run:
        path: sh
        args:
        - -exc
        - |
          apt-get update
          apt-get install -y curl
          curl https://bl.ocks.org/sharor/raw/4b2015849c31bfb860c6a021ba9ed63a/
    on_failure:
      put: slack-alert
      params:
        channel: '@albert'
        text: |
          The build failed. Please go correct it at:
          http://35.156.129.15//teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          http://35.156.129.15//builds/$BUILD_ID
  - task: link-checker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: praqma/linkchecker}
      run:
        path: sh
        args:
        - -exc
        - |
          linkchecker http://bl.ocks.org/sharor/raw/4b2015849c31bfb860c6a021ba9ed63a/
    on_failure:
      put: slack-alert
      params:
        channel: '@albert'
        text: |
          The build failed. Please go correct it at:
          http://35.156.129.15//teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          http://35.156.129.15//builds/$BUILD_ID
- name: update-production-site
  public: true
  plan:
  - get: repository
    passed: [test-site]
  - put: github-pages
    params:
      repository: repository
      force: true

resources:
- name: repository
  type: git
  source:
    uri: https://github.com/kvarak/concourse-workshop.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: gist
  type: git
  source:
    uri: https://gist.github.com/kvarak/0ae6f3a99889baa554b4685656ef91a0
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: github-pages
  type: git
  source:
    uri: https://github.com/kvarak/concourse-workshop.git
    branch: gh-pages
    username: {{github-username}}
    password: {{github-password}}

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
